#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

datadir=${dir}/db

# Test 1 seed
# WaznQ6iscGd2k3okPrFP4BUHegaQK7XhsSnWbSv96M832bRUn9bbKJTapqcCYvcX6S3vaNJLhrHcdfmsKFxR6c328aUxBTNc13
# honked patio justice ramped framed zeal jackets bevel lodge onion womanly twice obvious feel dormant gymnast gecko hexagon jabbed nurse metro upper aces asleep dormant

# Test 2 seed
# WaznTkr9mP9L9xKzgGfzAN9Q2L363z4Hccemor5EXAPd7kovSgPR75KXCb7s5hgQXSEbMZeeVs3zuHPUgakveiv564JNVj6Ssm
# loyal pledge after virtual zeal vivid mammal copy daily roared balding playful pinched revamp nexus fainted usual cobra gearbox square siren coils likewise movement gearbox

function wallet1()
{
	rm -f ${dir}/t1.cache
	${dir}/builder/build/dev/debug/bin/wazn-wallet-cli --stagenet --daemon-address 127.0.0.1:22787 --wallet-file ${dir}/t1 --password ""
}

function wallet2()
{
	rm -f ${dir}/t2.cache
	${dir}/builder/build/dev/debug/bin/wazn-wallet-cli --stagenet --daemon-address 127.0.0.1:33787 --wallet-file ${dir}/t2 --password ""
}

function createhwwallet()
{
	rm -f ${dir}/hw.cache
	rm -f ${dir}/hw.keys
	${dir}/builder/build/dev/debug/bin/wazn-wallet-cli --restore-height 1 --stagenet --daemon-address 127.0.0.1:22787 --generate-from-device ${dir}/hw --password "" --log-level 2
}

function hwwallet()
{
	${dir}/builder/build/dev/debug/bin/wazn-wallet-cli --stagenet --daemon-address 127.0.0.1:22787 --hw-device "Ledger" --wallet-file ${dir}/hw --password ""
}

function hwrwallet()
{
	${dir}/builder/build/dev/debug/bin/wazn-wallet-cli --stagenet --daemon-address 127.0.0.1:22787 --wallet-file ${dir}/hwr --password ""
}

function n1()
{
	${dir}/builder/build/dev/debug/bin/waznd --stagenet --data-dir ${datadir}/n1 --p2p-bind-port 22786 --rpc-bind-port 22787 --rpc-restricted-bind-port 22789 \
	--add-exclusive-node 127.0.0.1:33786 \
	--fixed-difficulty ${DIFF} --block-sync-size 10
}

function n2()
{
	${dir}/builder/build/dev/debug/bin/waznd --stagenet --data-dir ${datadir}/n2 --p2p-bind-port 33786 --rpc-bind-port 33787 --rpc-restricted-bind-port 22789 \
	--add-exclusive-node 127.0.0.1:22786 \
	--fixed-difficulty ${DIFF}  --block-sync-size 10
}

$1
